version: '3'

services:
  backend:
    env_file: ./backend/.env
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "stock-predictor-backend"
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "stock-predictor-frontend"
    ports:
      - "3000:80"
    links:
      - "backend:be"