name: Deploy to Heroku (Staging) #set whatevername you want to your github job
on:
  push:
    branches:
      - CB-31-deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0  # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          docker_compose_file: './src/docker-compose.heroku.yml' # set the path to the folder where the docker-compose file is located
          heroku_apps: '[{"imagename":"stock-predictor-frontend","appname":"stock-decider-frontend-stage","apptype":"web"},{"imagename":"stock-predictor-backend","appname":"stock-decider-backend-stage","apptype":"web"}]' # List of Docker Image name, Heroku app and Heroku app type